name: Generate Gitartwork

on: 
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *" # Tự động chạy lại mỗi 4 tiếng để cập nhật
  workflow_dispatch: # Cho phép bạn bấm chạy thủ công bất cứ lúc nào

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: jasineri/gitartwork@v1
        with:
           user_name: Nhan-create
           text: NHAN! # Chữ hiển thị trên lịch đóng góp (Tối đa khoảng 8 ký tự)
           
      - name: Set Git User
        run: |
          git config user.name "Nhan-create"
          git config user.email "nhan-create@users.noreply.github.com"
          
      - uses: jasineri/simple-push-action@v1
